export declare const textAlignCssPropertyNameList: readonly ("center" | "left" | "right" | "justify")[];
export declare const textTransformCssPropertyNameList: readonly ("capitalize" | "uppercase" | "lowercase")[];
export declare const displayCssPropertyNameList: readonly ("block" | "inline-block" | "inline" | "flex" | "inline-flex" | "grid" | "inline-grid")[];
export declare const alignContentCssPropertyNameList: readonly ("start" | "end" | "center" | "between" | "around" | "evenly" | "stretch")[];
export declare const alignItemsCssPropertyNameList: readonly ("start" | "end" | "center" | "stretch" | "baseline")[];
export declare const alignSelfCssPropertyNameList: readonly ("start" | "end" | "center" | "stretch" | "baseline" | "auto")[];
export declare const flexBasisCssPropertyNameList: readonly ("auto" | "0" | "25" | "33" | "50" | "75" | "100")[];
export declare const flexDirectionCssPropertyNameList: readonly ("column" | "row" | "column-reverse" | "row-reverse")[];
export declare const flexWrapCssPropertyNameList: readonly ("wrap" | "wrap-reverse" | "no-wrap")[];
export declare const justifyContentCssPropertyNameList: readonly ("start" | "end" | "center" | "between" | "around" | "evenly" | "stretch")[];
