version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - .:/var/www/app
    command: ['sh', '-c', 'npm ci && npm run start:storybook']
    ports:
      - 6006:6006
    tty: true
