name: restore-pnpm-cache
description: Restore pnpm Cache
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Restore pnpm Cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: cache-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: cache-node-modules-
    - name: Prepare project
      shell: bash
      run: pnpm prepare
