name: Run checks and tests

on: [pull_request]

jobs:
  setup:
    uses: ./.github/workflows/setup-nodejs-and-install-dependencies.yml

  commitlint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NPM Cache
        uses: ./.github/actions/restore-npm-cache

      - name: Lint commit
        run: npx commitlint --from=HEAD

  eslint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NPM Cache
        uses: ./.github/actions/restore-npm-cache

      - name: Lint code
        run: npm run lint:es

  stylelint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NPM Cache
        uses: ./.github/actions/restore-npm-cache

      - name: Lint code
        run: npm run lint:style

  compile:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NPM Cache
        uses: ./.github/actions/restore-npm-cache

      - name: Run Compile TypeScript
        run: npx tsc

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NPM Cache
        uses: ./.github/actions/restore-npm-cache

      - name: Run Tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NPM Cache
        uses: ./.github/actions/restore-npm-cache

      - name: Build Design System
        run: npm run build

  build-storybook:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NPM Cache
        uses: ./.github/actions/restore-npm-cache

      - name: Build Storybook
        run: npm run build:storybook
