name: Build and Deploy Storybook

on:
  push:
    branches:
      - master
jobs:
  setup:
    uses: ./.github/workflows/setup-nodejs-and-install-dependencies.yml

  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Storybook
        run: npm run build:storybook

      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
