name: Publish package to NPM

on:
  release:
    types: [created]

env:
  VITE_CDN_PATH: /

jobs:
  setup:
    uses: ./.github/workflows/setup-nodejs-and-install-dependencies.yml

  publish-package:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore NPM Cache
        uses: ./.github/actions/restore-npm-cache

      - name: Build Library
        run: npm run build

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@eleven-labs'

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
